#![warn(missing_docs)]
//! Shared parser test harness, golden fixtures, and equivalence infrastructure.
//!
//! This crate provides the testing backbone for TalkBank's two-parser strategy.
//! The tree-sitter parser (canonical, GLR-based, error-recovering) and the direct
//! parser (experimental, chumsky combinators, with selective recovery/leniency)
//! must produce semantically identical [`talkbank_model::ChatFile`] ASTs on all
//! well-formed full-file input. This crate enforces that contract.
//!
//! It should not assume tree-sitter fragment helpers are the oracle for direct-
//! parser fragment semantics. Fragment and recovery behavior need independent
//! direct-parser-focused coverage.
//!
//! # Architecture
//!
//! The crate serves two purposes:
//!
//! 1. **Library** -- reusable helpers consumed by integration tests in this crate
//!    and by other crates in the workspace.
//! 2. **Integration tests** -- the `tests/` directory contains per-file parser
//!    equivalence tests, spec-generated tests, golden word/tier validation, and
//!    property-based tests.
//!
//! ## Test categories
//!
//! | Test file | What it checks |
//! |-----------|----------------|
//! | `parser_equivalence_files` | Per-file equivalence on the 74-file reference corpus |
//! | `parser_equivalence_words` | Per-word equivalence on the golden word list |
//! | `generated_tests` / `generated` | Spec-generated parse + validation assertions |
//! | `golden_words_validation` | Round-trip fidelity of the golden word corpus |
//! | `golden_tiers_validation` | Round-trip fidelity of golden tier corpora |
//! | `property_tests` | Proptest-based structural invariants |
//!
//! ## Parser equivalence vs spec tests
//!
//! *Spec tests* (in `spec/constructs/` and `spec/errors/`) verify that individual
//! CHAT constructs parse to the expected CST/AST and that invalid input produces
//! the correct error codes. They are generated into this crate by `make test-gen`.
//!
//! *Parser equivalence tests* verify that the two parser implementations agree on
//! real-world files from the 74-file reference corpus at
//! `talkbank-chat/corpus/reference/`. They catch drift between parsers that spec
//! tests alone cannot detect, but they are strongest for whole-file behavior,
//! not as the oracle for legacy synthetic fragment APIs.
//!
//! # Running the tests
//!
//! ```bash
//! # All tests in this crate (nextest-compatible, parallel per-test)
//! cargo nextest run -p talkbank-parser-tests
//!
//! # Parser equivalence only (73 per-file tests)
//! cargo nextest run -p talkbank-parser-tests -E 'test(parser_equivalence)'
//!
//! # A single reference file
//! cargo nextest run -p talkbank-parser-tests -E 'test(some_filename)'
//!
//! # Golden word round-trip
//! cargo nextest run -p talkbank-parser-tests -E 'test(golden_words)'
//!
//! # Show output on failure
//! cargo nextest run -p talkbank-parser-tests --no-capture
//! ```
//!
//! # Module map
//!
//! | Module | Purpose |
//! |--------|---------|
//! | [`bug_annotations`] | Known-bug tracking via `golden_bugs.toml` (skip/expect-wrong/note) |
//! | [`feature_signature`] | Coarse word classification for deduplicating golden corpus |
//! | [`golden`] | Golden word and tier loaders, shared round-trip runner |
//! | [`snapshot`] | Cross-parser snapshot comparison infrastructure |
//! | [`template`] | [`ChatFileBuilder`] and [`MinimalChatFile`] for synthesizing valid CHAT |
//! | [`test_error`] | Unified error type for test binaries and integration suites |
//!
//! # Examples
//!
//! Build a minimal CHAT file for a test:
//!
//! ```
//! use talkbank_parser_tests::minimal_chat_file;
//!
//! let content = minimal_chat_file();
//! assert!(content.contains("@Begin"));
//! assert!(content.contains("@End"));
//! ```
//!
//! Build a multi-utterance file with the builder:
//!
//! ```
//! use talkbank_parser_tests::ChatFileBuilder;
//!
//! let content = ChatFileBuilder::new()
//!     .speaker("CHI", "Target_Child")
//!     .utterance("CHI", "hello world .")
//!     .utterance("CHI", "goodbye .")
//!     .build();
//! assert!(content.contains("*CHI:\thello world ."));
//! ```
//!
//! # Related CHAT Manual Sections
//!
//! - <https://talkbank.org/0info/manuals/CHAT.html#File_Format>
//! - <https://talkbank.org/0info/manuals/CHAT.html#Main_Tier>
//! - <https://talkbank.org/0info/manuals/CHAT.html#Dependent_Tiers>

pub mod bug_annotations;

/// Auto-generated grammar-aware CST traversal (from grammar.json).
///
/// Generated by `tree-sitter-node-types` from the CHAT grammar.
/// Do not edit manually — regenerate with:
/// ```sh
/// cargo run --example generate_traversal -p tree-sitter-node-types -- \
///   grammar/src/grammar.json grammar/src/node-types.json \
///   --skip whitespaces > crates/talkbank-parser-tests/src/generated_traversal.rs
/// ```
#[allow(
    dead_code,
    clippy::all,
    clippy::pedantic,
    clippy::nursery,
    missing_docs,
    unused_variables,
    unused_mut
)]
pub mod generated_traversal;
pub mod error_corpus_gen;
pub mod feature_signature;
pub mod snapshot;
pub mod template;
pub mod test_error;

pub use bug_annotations::{BugAction, BugAnnotation, GoldenBugs};
pub use feature_signature::WordFeatureSignature;
pub use template::{ChatFileBuilder, MinimalChatFile, minimal_chat_file};

pub mod golden {
    //! Golden test helpers for parser implementations.

    use talkbank_model::ErrorCollector;
    use talkbank_model::model::WriteChat;
    use talkbank_model::ParseOutcome;
    use talkbank_parser::TreeSitterParser;

    const GOLDEN_WORD_FILE: &str = include_str!("../golden_words.txt");
    const GOLDEN_WORD_FEATURED_FILE: &str = include_str!("../golden_words_featured.txt");
    const GOLDEN_WORD_MINIMAL_FILE: &str = include_str!("../golden_words_minimal.txt");
    const GOLDEN_MAIN_TIER_FILE: &str = include_str!("../golden_main_tiers.txt");
    const GOLDEN_MOR_TIER_FILE: &str = include_str!("../golden_mor_tiers.txt");
    const GOLDEN_GRA_TIER_FILE: &str = include_str!("../golden_gra_tiers.txt");
    const GOLDEN_PHO_TIER_FILE: &str = include_str!("../golden_pho_tiers.txt");
    const GOLDEN_SIN_TIER_FILE: &str = include_str!("../golden_sin_tiers.txt");
    const GOLDEN_WOR_TIER_FILE: &str = include_str!("../golden_wor_tiers.txt");
    const GOLDEN_COM_TIER_FILE: &str = include_str!("../golden_com_tiers.txt");

    /// Load the canonical word list used by golden tests.
    ///
    /// This file is generated from the reference corpus so it represents
    /// known-good CHAT words. Run
    /// `cargo run -p talkbank-parser-tests --bin generate-golden-words -- --corpus-root corpus/reference`
    /// after editing the reference corpus to regenerate the list.
    ///
    /// For expensive cross-parser equivalence tests, use `golden_words_featured()` instead.
    pub fn golden_words() -> Vec<&'static str> {
        GOLDEN_WORD_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Load the MINIMAL word list for fast core tests (<1 second).
    ///
    /// This is the smallest possible test set (~47 words) with:
    /// - EXACTLY ONE representative per unique feature signature
    /// - 2-3 plain text representatives
    ///
    /// Use this for:
    /// - Fast CI tests (runs in <1 second)
    /// - Core feature regression detection
    /// - TDD feedback loop
    ///
    /// For more comprehensive testing, use `golden_words_featured()` (84 words).
    /// For full corpus validation, use `golden_words()` (768 words).
    ///
    /// Regenerate with:
    /// `cargo run -p talkbank-parser-tests --bin audit_golden_words`
    pub fn golden_words_minimal() -> Vec<&'static str> {
        GOLDEN_WORD_MINIMAL_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Load the curated featured word list for cross-parser equivalence testing.
    ///
    /// This is a subset (~84 words) of `golden_words.txt` with:
    /// - 1-3 representatives per unique feature signature
    /// - 5 plain text representatives
    ///
    /// Use this for expensive cross-parser equivalence tests where testing all 768 words
    /// would be wasteful (36% are plain text exercising identical code paths).
    ///
    /// Use `golden_words_minimal()` for fast core tests.
    /// Use `golden_words()` for cheap round-trip sanity tests.
    ///
    /// Regenerate with:
    /// `cargo run -p talkbank-parser-tests --bin audit_golden_words`
    pub fn golden_words_featured() -> Vec<&'static str> {
        GOLDEN_WORD_FEATURED_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Load the canonical main tier list used by golden tests.
    ///
    /// This file is generated from the reference corpus so it represents
    /// known-good CHAT main tiers. Run
    /// `cargo run -p talkbank-parser-tests --bin generate-golden-main-tiers -- --corpus-root corpus/reference`
    /// after editing the reference corpus to regenerate the list.
    pub fn golden_main_tiers() -> Vec<&'static str> {
        GOLDEN_MAIN_TIER_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Load the canonical %mor tier list used by golden tests.
    ///
    /// This file is generated from the reference corpus so it represents
    /// known-good CHAT %mor tiers. Run
    /// `cargo run -p talkbank-parser-tests --bin generate-golden-mor-tiers -- --corpus-root corpus/reference`
    /// after editing the reference corpus to regenerate the list.
    pub fn golden_mor_tiers() -> Vec<&'static str> {
        GOLDEN_MOR_TIER_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Load the canonical %gra tier list used by golden tests.
    ///
    /// This file is generated from the reference corpus so it represents
    /// known-good CHAT %gra tiers. Run
    /// `cargo run -p talkbank-parser-tests --bin generate-golden-gra-tiers -- --corpus-root corpus/reference`
    /// after editing the reference corpus to regenerate the list.
    pub fn golden_gra_tiers() -> Vec<&'static str> {
        GOLDEN_GRA_TIER_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Load the canonical %pho tier list used by golden tests.
    ///
    /// This file is generated from the reference corpus so it represents
    /// known-good CHAT %pho tiers. Run
    /// `cargo run -p talkbank-parser-tests --bin generate-golden-pho-tiers -- --corpus-root corpus/reference`
    /// after editing the reference corpus to regenerate the list.
    pub fn golden_pho_tiers() -> Vec<&'static str> {
        GOLDEN_PHO_TIER_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Load the canonical %sin tier list used by golden tests.
    ///
    /// This file is generated from the reference corpus so it represents
    /// known-good CHAT %sin tiers. Run
    /// `cargo run -p talkbank-parser-tests --bin generate_golden_sin_tiers -- --corpus-root corpus/reference`
    /// after editing the reference corpus to regenerate the list.
    pub fn golden_sin_tiers() -> Vec<&'static str> {
        GOLDEN_SIN_TIER_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Load the canonical %wor tier list used by golden tests.
    ///
    /// This file is generated from the reference corpus so it represents
    /// known-good CHAT %wor tiers. Run
    /// `cargo run -p talkbank-parser-tests --bin generate_golden_wor_tiers -- --corpus-root corpus/reference`
    /// after editing the reference corpus to regenerate the list.
    pub fn golden_wor_tiers() -> Vec<&'static str> {
        GOLDEN_WOR_TIER_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Load the canonical %com tier list used by golden tests.
    ///
    /// This file is generated from the reference corpus so it represents
    /// known-good CHAT %com tiers. Run
    /// `cargo run -p talkbank-parser-tests --bin generate_golden_com_tiers -- --corpus-root corpus/reference`
    /// after editing the reference corpus to regenerate the list.
    pub fn golden_com_tiers() -> Vec<&'static str> {
        GOLDEN_COM_TIER_FILE
            .lines()
            .filter(|line| !is_blank_or_comment(line))
            .collect()
    }

    /// Returns whether blank or comment.
    fn is_blank_or_comment(line: &str) -> bool {
        for ch in line.chars() {
            if ch.is_whitespace() {
                continue;
            }
            return ch == '#';
        }
        true
    }

    /// Run the shared golden word round-trip test.
    pub fn run_word_roundtrip(parser: &TreeSitterParser) {
        let words = golden_words();
        for word in words {
            let sink = ErrorCollector::new();
            let parsed = parser.parse_word_fragment(word, 0, &sink);

            assert!(
                sink.is_empty(),
                "unexpected errors parsing `{}`: {:?}",
                word,
                sink.to_vec()
            );

            assert!(
                matches!(parsed, ParseOutcome::Parsed(_)),
                "parser rejected word `{}` despite no sink errors",
                word
            );
            let ParseOutcome::Parsed(parsed) = parsed else {
                continue;
            };

            let mut serialized = String::new();
            assert!(
                parsed.write_chat(&mut serialized).is_ok(),
                "failed to serialize word `{}`",
                word
            );
            assert_eq!(
                serialized, word,
                "word roundtrip changed representation"
            );
        }
    }
}
