//! Generated node type constants from tree-sitter grammar.
//!
//! DO NOT EDIT THIS FILE MANUALLY!
//! This file is auto-generated by `scripts/generate-node-types.js`.
//!
//! To regenerate:
//! ```sh
//! node scripts/generate-node-types.js > crates/talkbank-parser/src/node_types.rs
//! ```
//!
//! All 372 named node types from the tree-sitter CHAT grammar
//! are available as compile-time `&str` constants.
//!
//! # Example
//! ```
//! use talkbank_parser::node_types::BEGIN_HEADER;
//!
//! assert_eq!(BEGIN_HEADER, "begin_header");
//! ```
//!
//! # Related CHAT Manual Sections
//!
//! - <https://talkbank.org/0info/manuals/CHAT.html#File_Headers>
//! - <https://talkbank.org/0info/manuals/CHAT.html#Main_Tier>
//! - <https://talkbank.org/0info/manuals/CHAT.html#Dependent_Tiers>

#![allow(dead_code)]
#![allow(clippy::doc_markdown)]

// === Document Structure ===

/// Continuation of a multi-line tier.
pub const CONTINUATION: &str = "continuation";
/// Generic header line.
pub const HEADER: &str = "header";
/// Gap between header sections.
pub const HEADER_GAP: &str = "header_gap";
/// Header separator between prefix and content.
pub const HEADER_SEP: &str = "header_sep";
/// Single line in the CHAT document.
pub const LINE: &str = "line";
/// Header line appearing before `@Begin`.
pub const PRE_BEGIN_HEADER: &str = "pre_begin_header";
/// Complete utterance (main tier + dependent tiers).
pub const UTTERANCE: &str = "utterance";
/// End boundary of an utterance.
pub const UTTERANCE_END: &str = "utterance_end";

// === Required Headers ===

/// `@Begin` header marking start of transcript.
pub const BEGIN_HEADER: &str = "begin_header";
/// `@End` header marking end of transcript.
pub const END_HEADER: &str = "end_header";
/// `@UTF8` header declaring file encoding.
pub const UTF8_HEADER: &str = "utf8_header";

// === Participant Headers (@Participants, @ID) ===

/// Age field in `@ID` header.
pub const ID_AGE: &str = "id_age";
/// Parsed contents of an `@ID` header.
pub const ID_CONTENTS: &str = "id_contents";
/// Corpus name field in `@ID` header.
pub const ID_CORPUS: &str = "id_corpus";
/// Custom extension field in `@ID` header.
pub const ID_CUSTOM_FIELD: &str = "id_custom_field";
/// Education field in `@ID` header.
pub const ID_EDUCATION: &str = "id_education";
/// Group field in `@ID` header.
pub const ID_GROUP: &str = "id_group";
/// `@ID` header line for participant metadata.
pub const ID_HEADER: &str = "id_header";
/// Languages field in `@ID` header.
pub const ID_LANGUAGES: &str = "id_languages";
/// `@ID` header prefix.
pub const ID_PREFIX: &str = "id_prefix";
/// Role field in `@ID` header.
pub const ID_ROLE: &str = "id_role";
/// Socioeconomic status field in `@ID` header.
pub const ID_SES: &str = "id_ses";
/// Sex field in `@ID` header.
pub const ID_SEX: &str = "id_sex";
/// Speaker code field in `@ID` header.
pub const ID_SPEAKER: &str = "id_speaker";
/// Single participant entry in `@Participants` header.
pub const PARTICIPANT: &str = "participant";
/// Word within a participant description.
pub const PARTICIPANT_WORD: &str = "participant_word";
/// Parsed contents of `@Participants` header.
pub const PARTICIPANTS_CONTENTS: &str = "participants_contents";
/// `@Participants` header line.
pub const PARTICIPANTS_HEADER: &str = "participants_header";
/// `@Participants` header prefix.
pub const PARTICIPANTS_PREFIX: &str = "participants_prefix";

// === Structured Headers ===

/// Age in `years;months.days` format.
pub const AGE_FORMAT: &str = "age_format";
/// Audio media type value `audio`.
pub const AUDIO_VALUE: &str = "audio_value";
/// Parsed contents of a `@Date` header.
pub const DATE_CONTENTS: &str = "date_contents";
/// `@Date` header line.
pub const DATE_HEADER: &str = "date_header";
/// `@Date` header prefix.
pub const DATE_PREFIX: &str = "date_prefix";
/// Female sex value in `@ID` header.
pub const FEMALE_VALUE: &str = "female_value";
/// ISO language code.
pub const LANGUAGE_CODE: &str = "language_code";
/// Parsed contents of `@Languages` header.
pub const LANGUAGES_CONTENTS: &str = "languages_contents";
/// `@Languages` header line.
pub const LANGUAGES_HEADER: &str = "languages_header";
/// `@Languages` header prefix.
pub const LANGUAGES_PREFIX: &str = "languages_prefix";
/// Male sex value in `@ID` header.
pub const MALE_VALUE: &str = "male_value";
/// Parsed contents of `@Media` header.
pub const MEDIA_CONTENTS: &str = "media_contents";
/// Media filename in `@Media` header.
pub const MEDIA_FILENAME: &str = "media_filename";
/// `@Media` header line.
pub const MEDIA_HEADER: &str = "media_header";
/// `@Media` header prefix.
pub const MEDIA_PREFIX: &str = "media_prefix";
/// Media availability status.
pub const MEDIA_STATUS: &str = "media_status";
/// Media type (audio or video).
pub const MEDIA_TYPE: &str = "media_type";
/// Media URL in `@Media` header.
pub const MEDIA_URL: &str = "media_url";
/// Missing or unspecified value placeholder.
pub const MISSING_VALUE: &str = "missing_value";
/// No-transcription value for media status.
pub const NOTRANS_VALUE: &str = "notrans_value";
/// `@Number` header line.
pub const NUMBER_HEADER: &str = "number_header";
/// Option value in `@Number` header.
pub const NUMBER_OPTION: &str = "number_option";
/// `@Number` header prefix.
pub const NUMBER_PREFIX: &str = "number_prefix";
/// Name of an option in `@Options` header.
pub const OPTION_NAME: &str = "option_name";
/// Parsed contents of `@Options` header.
pub const OPTIONS_CONTENTS: &str = "options_contents";
/// `@Options` header line.
pub const OPTIONS_HEADER: &str = "options_header";
/// `@Options` header prefix.
pub const OPTIONS_PREFIX: &str = "options_prefix";
/// `@Recording Quality` header line.
pub const RECORDING_QUALITY_HEADER: &str = "recording_quality_header";
/// Option in `@Recording Quality` header.
pub const RECORDING_QUALITY_OPTION: &str = "recording_quality_option";
/// `@Recording Quality` header prefix.
pub const RECORDING_QUALITY_PREFIX: &str = "recording_quality_prefix";
/// Parsed contents of `@Time Duration` header.
pub const TIME_DURATION_CONTENTS: &str = "time_duration_contents";
/// `@Time Duration` header line.
pub const TIME_DURATION_HEADER: &str = "time_duration_header";
/// `@Time Duration` header prefix.
pub const TIME_DURATION_PREFIX: &str = "time_duration_prefix";
/// `@Time Start` header line.
pub const TIME_START_HEADER: &str = "time_start_header";
/// `@Time Start` header prefix.
pub const TIME_START_PREFIX: &str = "time_start_prefix";
/// `@Transcription` header line.
pub const TRANSCRIPTION_HEADER: &str = "transcription_header";
/// Option in `@Transcription` header.
pub const TRANSCRIPTION_OPTION: &str = "transcription_option";
/// `@Transcription` header prefix.
pub const TRANSCRIPTION_PREFIX: &str = "transcription_prefix";
/// Activity type in `@Types` header.
pub const TYPES_ACTIVITY: &str = "types_activity";
/// Design type in `@Types` header.
pub const TYPES_DESIGN: &str = "types_design";
/// Group type in `@Types` header.
pub const TYPES_GROUP: &str = "types_group";
/// `@Types` header line.
pub const TYPES_HEADER: &str = "types_header";
/// `@Types` header prefix.
pub const TYPES_PREFIX: &str = "types_prefix";
/// Unlinked media value.
pub const UNLINKED_VALUE: &str = "unlinked_value";
/// Video media type value `video`.
pub const VIDEO_VALUE: &str = "video_value";

// === Text Headers ===

/// `%act` tier prefix marker.
pub const ACT_TIER_PREFIX: &str = "act_tier_prefix";
/// `@Activities` header line.
pub const ACTIVITIES_HEADER: &str = "activities_header";
/// `@Activities` header prefix.
pub const ACTIVITIES_PREFIX: &str = "activities_prefix";
/// `%add` tier prefix marker.
pub const ADD_TIER_PREFIX: &str = "add_tier_prefix";
/// `%alt` tier prefix marker.
pub const ALT_TIER_PREFIX: &str = "alt_tier_prefix";
/// `@Bck` background header line.
pub const BCK_HEADER: &str = "bck_header";
/// `@Bck` header prefix.
pub const BCK_PREFIX: &str = "bck_prefix";
/// `@Bg` background information header.
pub const BG_HEADER: &str = "bg_header";
/// `@Bg` header prefix.
pub const BG_PREFIX: &str = "bg_prefix";
/// `@Birth of` header for participant birth date.
pub const BIRTH_OF_HEADER: &str = "birth_of_header";
/// `@Birth of` header prefix.
pub const BIRTH_OF_PREFIX: &str = "birth_of_prefix";
/// `@Birthplace of` header for participant birthplace.
pub const BIRTHPLACE_OF_HEADER: &str = "birthplace_of_header";
/// `@Birthplace of` header prefix.
pub const BIRTHPLACE_OF_PREFIX: &str = "birthplace_of_prefix";
/// `@Blank` header line.
pub const BLANK_HEADER: &str = "blank_header";
/// `@Blank` header prefix.
pub const BLANK_PREFIX: &str = "blank_prefix";
/// `%cod` tier prefix marker.
pub const COD_TIER_PREFIX: &str = "cod_tier_prefix";
/// `%coh` tier prefix marker.
pub const COH_TIER_PREFIX: &str = "coh_tier_prefix";
/// `@ColorWords` header line.
pub const COLOR_WORDS_HEADER: &str = "color_words_header";
/// `@ColorWords` header prefix.
pub const COLOR_WORDS_PREFIX: &str = "color_words_prefix";
/// `%com` tier prefix marker.
pub const COM_TIER_PREFIX: &str = "com_tier_prefix";
/// `@Comment` header line.
pub const COMMENT_HEADER: &str = "comment_header";
/// `@Comment` header prefix.
pub const COMMENT_PREFIX: &str = "comment_prefix";
/// `%def` tier prefix marker.
pub const DEF_TIER_PREFIX: &str = "def_tier_prefix";
/// `@Eg` example header line.
pub const EG_HEADER: &str = "eg_header";
/// `@Eg` header prefix.
pub const EG_PREFIX: &str = "eg_prefix";
/// `%eng` tier prefix marker.
pub const ENG_TIER_PREFIX: &str = "eng_tier_prefix";
/// `%err` tier prefix marker.
pub const ERR_TIER_PREFIX: &str = "err_tier_prefix";
/// `%exp` tier prefix marker.
pub const EXP_TIER_PREFIX: &str = "exp_tier_prefix";
/// `%fac` tier prefix marker.
pub const FAC_TIER_PREFIX: &str = "fac_tier_prefix";
/// `%flo` tier prefix marker.
pub const FLO_TIER_PREFIX: &str = "flo_tier_prefix";
/// `@Font` header line.
pub const FONT_HEADER: &str = "font_header";
/// `@Font` header prefix.
pub const FONT_PREFIX: &str = "font_prefix";
/// `@G` header line.
pub const G_HEADER: &str = "g_header";
/// `@G` header prefix.
pub const G_PREFIX: &str = "g_prefix";
/// `%gls` tier prefix marker.
pub const GLS_TIER_PREFIX: &str = "gls_tier_prefix";
/// `%gpx` tier prefix marker.
pub const GPX_TIER_PREFIX: &str = "gpx_tier_prefix";
/// `%int` tier prefix marker.
pub const INT_TIER_PREFIX: &str = "int_tier_prefix";
/// `@L1 of` header for participant first language.
pub const L1_OF_HEADER: &str = "l1_of_header";
/// `@L1 of` header prefix.
pub const L1_OF_PREFIX: &str = "l1_of_prefix";
/// `@Location` header line.
pub const LOCATION_HEADER: &str = "location_header";
/// `@Location` header prefix.
pub const LOCATION_PREFIX: &str = "location_prefix";
/// `%mod` tier prefix marker.
pub const MOD_TIER_PREFIX: &str = "mod_tier_prefix";
/// CST node type: `modsyl_tier_prefix`.
pub const MODSYL_TIER_PREFIX: &str = "modsyl_tier_prefix";
/// `@New Episode` header line.
pub const NEW_EPISODE_HEADER: &str = "new_episode_header";
/// `@New Episode` header prefix.
pub const NEW_EPISODE_PREFIX: &str = "new_episode_prefix";
/// `%ort` tier prefix marker.
pub const ORT_TIER_PREFIX: &str = "ort_tier_prefix";
/// `@Page` header line.
pub const PAGE_HEADER: &str = "page_header";
/// `@Page` header prefix.
pub const PAGE_PREFIX: &str = "page_prefix";
/// `%par` tier prefix marker.
pub const PAR_TIER_PREFIX: &str = "par_tier_prefix";
/// CST node type: `phoaln_tier_prefix`.
pub const PHOALN_TIER_PREFIX: &str = "phoaln_tier_prefix";
/// CST node type: `phosyl_tier_prefix`.
pub const PHOSYL_TIER_PREFIX: &str = "phosyl_tier_prefix";
/// `@PID` persistent identifier header line.
pub const PID_HEADER: &str = "pid_header";
/// `@PID` header prefix.
pub const PID_PREFIX: &str = "pid_prefix";
/// `@Room Layout` header line.
pub const ROOM_LAYOUT_HEADER: &str = "room_layout_header";
/// `@Room Layout` header prefix.
pub const ROOM_LAYOUT_PREFIX: &str = "room_layout_prefix";
/// `%sit` tier prefix marker.
pub const SIT_TIER_PREFIX: &str = "sit_tier_prefix";
/// `@Situation` header line.
pub const SITUATION_HEADER: &str = "situation_header";
/// `@Situation` header prefix.
pub const SITUATION_PREFIX: &str = "situation_prefix";
/// `%spa` tier prefix marker.
pub const SPA_TIER_PREFIX: &str = "spa_tier_prefix";
/// `@T` time header line.
pub const T_HEADER: &str = "t_header";
/// `@T` header prefix.
pub const T_PREFIX: &str = "t_prefix";
/// `@Tape Location` header line.
pub const TAPE_LOCATION_HEADER: &str = "tape_location_header";
/// `@Tape Location` header prefix.
pub const TAPE_LOCATION_PREFIX: &str = "tape_location_prefix";
/// `@Thumbnail` header line.
pub const THUMBNAIL_HEADER: &str = "thumbnail_header";
/// `@Thumbnail` header prefix.
pub const THUMBNAIL_PREFIX: &str = "thumbnail_prefix";
/// `%tim` tier prefix marker.
pub const TIM_TIER_PREFIX: &str = "tim_tier_prefix";
/// `@Transcriber` header line.
pub const TRANSCRIBER_HEADER: &str = "transcriber_header";
/// `@Transcriber` header prefix.
pub const TRANSCRIBER_PREFIX: &str = "transcriber_prefix";
/// Unrecognized header (parsed generically).
pub const UNSUPPORTED_HEADER: &str = "unsupported_header";
/// Prefix of an unrecognized header.
pub const UNSUPPORTED_HEADER_PREFIX: &str = "unsupported_header_prefix";
/// Prefix of an unrecognized dependent tier.
pub const UNSUPPORTED_TIER_PREFIX: &str = "unsupported_tier_prefix";
/// `@Videos` header line.
pub const VIDEOS_HEADER: &str = "videos_header";
/// `@Videos` header prefix.
pub const VIDEOS_PREFIX: &str = "videos_prefix";
/// `@Warning` header line.
pub const WARNING_HEADER: &str = "warning_header";
/// `@Warning` header prefix.
pub const WARNING_PREFIX: &str = "warning_prefix";
/// `@Window` header line.
pub const WINDOW_HEADER: &str = "window_header";
/// `@Window` header prefix.
pub const WINDOW_PREFIX: &str = "window_prefix";
/// CST node type: `word_prefix`.
pub const WORD_PREFIX: &str = "word_prefix";
/// `%x` tier prefix marker.
pub const X_TIER_PREFIX: &str = "x_tier_prefix";

// === Main Tier ===

/// Main speaker tier line.
pub const MAIN_TIER: &str = "main_tier";
/// Speaker code on a main tier line.
pub const SPEAKER: &str = "speaker";
/// Body content of a tier line.
pub const TIER_BODY: &str = "tier_body";
/// Separator between tier prefix and body.
pub const TIER_SEP: &str = "tier_sep";

// === Terminators ===

/// Broken question terminator `+?`.
pub const BROKEN_QUESTION: &str = "broken_question";
/// Exclamation terminator `!`.
pub const EXCLAMATION: &str = "exclamation";
/// Interrupted question terminator `+/?`.
pub const INTERRUPTED_QUESTION: &str = "interrupted_question";
/// Interruption terminator `+/.`.
pub const INTERRUPTION: &str = "interruption";
/// Period terminator `.`.
pub const PERIOD: &str = "period";
/// Question terminator `?`.
pub const QUESTION: &str = "question";
/// Self-interrupted question terminator `+//?`.
pub const SELF_INTERRUPTED_QUESTION: &str = "self_interrupted_question";
/// Self-interruption terminator `+//.`.
pub const SELF_INTERRUPTION: &str = "self_interruption";
/// Utterance terminator node.
pub const TERMINATOR: &str = "terminator";
/// Trailing off terminator `+...`.
pub const TRAILING_OFF: &str = "trailing_off";
/// Trailing off question terminator `+..?`.
pub const TRAILING_OFF_QUESTION: &str = "trailing_off_question";
/// Unmarked ending terminator.
pub const UNMARKED_ENDING: &str = "unmarked_ending";

// === Linkers ===

/// Single linker element.
pub const LINKER: &str = "linker";
/// Lazy overlap linker.
pub const LINKER_LAZY_OVERLAP: &str = "linker_lazy_overlap";
/// Quick uptake linker.
pub const LINKER_QUICK_UPTAKE: &str = "linker_quick_uptake";
/// Quick uptake with overlap linker.
pub const LINKER_QUICK_UPTAKE_OVERLAP: &str = "linker_quick_uptake_overlap";
/// Quotation-follows linker.
pub const LINKER_QUOTATION_FOLLOWS: &str = "linker_quotation_follows";
/// Self-completion linker.
pub const LINKER_SELF_COMPLETION: &str = "linker_self_completion";
/// Container for utterance linker markers.
pub const LINKERS: &str = "linkers";

// === Content Items and Words ===

/// Content item inside a bracketed group.
pub const BASE_CONTENT_ITEM: &str = "base_content_item";
/// Single content item in an utterance.
pub const CONTENT_ITEM: &str = "content_item";
/// Generic content container node.
pub const CONTENTS: &str = "contents";
/// Non-word element in utterance.
pub const NONWORD: &str = "nonword";
/// Non-word element with optional annotations.
pub const NONWORD_WITH_OPTIONAL_ANNOTATIONS: &str = "nonword_with_optional_annotations";
/// Remaining text to end of line.
pub const REST_OF_LINE: &str = "rest_of_line";
/// Standalone word in content.
pub const STANDALONE_WORD: &str = "standalone_word";
/// Text segment within content.
pub const TEXT_SEGMENT: &str = "text_segment";
/// Word with optional annotation brackets.
pub const WORD_WITH_OPTIONAL_ANNOTATIONS: &str = "word_with_optional_annotations";

// === Events ===

/// Event in an utterance.
pub const EVENT: &str = "event";
/// Event marker symbol.
pub const EVENT_MARKER: &str = "event_marker";
/// Segment within an event.
pub const EVENT_SEGMENT: &str = "event_segment";
/// Nonvocal event marker.
pub const NONVOCAL: &str = "nonvocal";
/// Nonvocal begin marker for spanning events.
pub const NONVOCAL_BEGIN: &str = "nonvocal_begin";
/// Nonvocal begin marker symbol.
pub const NONVOCAL_BEGIN_MARKER: &str = "nonvocal_begin_marker";
/// Nonvocal end marker for spanning events.
pub const NONVOCAL_END: &str = "nonvocal_end";
/// Nonvocal end marker symbol.
pub const NONVOCAL_END_MARKER: &str = "nonvocal_end_marker";
/// Simple (non-spanning) nonvocal event.
pub const NONVOCAL_SIMPLE: &str = "nonvocal_simple";
/// Other spoken event marker.
pub const OTHER_SPOKEN_EVENT: &str = "other_spoken_event";

// === Groups ===

/// Base-level annotation on a content item.
pub const BASE_ANNOTATION: &str = "base_annotation";
/// Container for base annotations on a content item.
pub const BASE_ANNOTATIONS: &str = "base_annotations";
/// Final codes at end of utterance before terminator.
pub const FINAL_CODES: &str = "final_codes";
/// Angle-bracketed group with annotations `<...> [...]`.
pub const GROUP_WITH_ANNOTATIONS: &str = "group_with_annotations";
/// Main phonological group aligned to `%pho` tier.
pub const MAIN_PHO_GROUP: &str = "main_pho_group";
/// Main group aligned to `%sin` tier.
pub const MAIN_SIN_GROUP: &str = "main_sin_group";
/// Quoted speech group.
pub const QUOTATION: &str = "quotation";

// === Annotations ===

/// Alternative transcription annotation `[=? text]`.
pub const ALT_ANNOTATION: &str = "alt_annotation";
/// Duration annotation on a content item.
pub const DURATION_ANNOTATION: &str = "duration_annotation";
/// Error marker annotation `[*]`.
pub const ERROR_MARKER_ANNOTATION: &str = "error_marker_annotation";
/// Exclude marker for omitting content from analysis.
pub const EXCLUDE_MARKER: &str = "exclude_marker";
/// Explanation annotation `[= text]`.
pub const EXPLANATION_ANNOTATION: &str = "explanation_annotation";
/// Free coding annotation `[+ text]`.
pub const FREECODE: &str = "freecode";
/// Long feature spanning multiple words.
pub const LONG_FEATURE: &str = "long_feature";
/// Long feature begin node.
pub const LONG_FEATURE_BEGIN: &str = "long_feature_begin";
/// Long feature begin marker symbol.
pub const LONG_FEATURE_BEGIN_MARKER: &str = "long_feature_begin_marker";
/// Long feature end node.
pub const LONG_FEATURE_END: &str = "long_feature_end";
/// Long feature end marker symbol.
pub const LONG_FEATURE_END_MARKER: &str = "long_feature_end_marker";
/// Label text for a long feature.
pub const LONG_FEATURE_LABEL: &str = "long_feature_label";
/// Paralinguistic annotation.
pub const PARA_ANNOTATION: &str = "para_annotation";
/// Percent annotation on a content item.
pub const PERCENT_ANNOTATION: &str = "percent_annotation";
/// Postcode annotation `[+ code]`.
pub const POSTCODE: &str = "postcode";
/// Replacement annotation `[: text]`.
pub const REPLACEMENT: &str = "replacement";
/// Complete retrace marker `[/]`.
pub const RETRACE_COMPLETE: &str = "retrace_complete";
/// Multiple retrace marker `[///]`.
pub const RETRACE_MULTIPLE: &str = "retrace_multiple";
/// Partial retrace marker `[//]`.
pub const RETRACE_PARTIAL: &str = "retrace_partial";
/// Reformulation retrace marker.
pub const RETRACE_REFORMULATION: &str = "retrace_reformulation";
/// Uncertain retrace marker.
pub const RETRACE_UNCERTAIN: &str = "retrace_uncertain";
/// Scoped best-guess marker `[?]`.
pub const SCOPED_BEST_GUESS: &str = "scoped_best_guess";
/// Scoped contrastive stressing marker.
pub const SCOPED_CONTRASTIVE_STRESSING: &str = "scoped_contrastive_stressing";
/// Scoped stressing marker.
pub const SCOPED_STRESSING: &str = "scoped_stressing";
/// Scoped uncertain transcription marker.
pub const SCOPED_UNCERTAIN: &str = "scoped_uncertain";
/// Tag marker for coded items.
pub const TAG_MARKER: &str = "tag_marker";
/// Underline begin marker.
pub const UNDERLINE_BEGIN: &str = "underline_begin";
/// Underline end marker.
pub const UNDERLINE_END: &str = "underline_end";
/// Vocative marker for addressee names.
pub const VOCATIVE_MARKER: &str = "vocative_marker";

// === Overlap ===

/// Indexed overlap-follows marker.
pub const INDEXED_OVERLAP_FOLLOWS: &str = "indexed_overlap_follows";
/// Indexed overlap-precedes marker.
pub const INDEXED_OVERLAP_PRECEDES: &str = "indexed_overlap_precedes";
/// Overlap point marker in utterance.
pub const OVERLAP_POINT: &str = "overlap_point";

// === Prosody (Pauses and Intonation) ===

/// Falling-to-low intonation contour marker.
pub const FALLING_TO_LOW: &str = "falling_to_low";
/// Falling-to-mid intonation contour marker.
pub const FALLING_TO_MID: &str = "falling_to_mid";
/// Level pitch intonation contour marker.
pub const LEVEL_PITCH: &str = "level_pitch";
/// Pause token in utterance.
pub const PAUSE_TOKEN: &str = "pause_token";
/// Rising-to-high intonation contour marker.
pub const RISING_TO_HIGH: &str = "rising_to_high";
/// Rising-to-mid intonation contour marker.
pub const RISING_TO_MID: &str = "rising_to_mid";

// === Conversation Analysis Markers ===

/// Conversation analysis continuation marker.
pub const CA_CONTINUATION_MARKER: &str = "ca_continuation_marker";
/// Conversation analysis no-break marker.
pub const CA_NO_BREAK: &str = "ca_no_break";
/// Conversation analysis no-break linker.
pub const CA_NO_BREAK_LINKER: &str = "ca_no_break_linker";
/// Conversation analysis technical break marker.
pub const CA_TECHNICAL_BREAK: &str = "ca_technical_break";
/// Conversation analysis technical break linker.
pub const CA_TECHNICAL_BREAK_LINKER: &str = "ca_technical_break_linker";

// === Dependent Tiers ===

/// `%act` speech act dependent tier.
pub const ACT_DEPENDENT_TIER: &str = "act_dependent_tier";
/// `%add` addressee dependent tier.
pub const ADD_DEPENDENT_TIER: &str = "add_dependent_tier";
/// `%alt` alternative dependent tier.
pub const ALT_DEPENDENT_TIER: &str = "alt_dependent_tier";
/// `%cod` coding dependent tier.
pub const COD_DEPENDENT_TIER: &str = "cod_dependent_tier";
/// `%coh` cohesion dependent tier.
pub const COH_DEPENDENT_TIER: &str = "coh_dependent_tier";
/// `%com` comment dependent tier.
pub const COM_DEPENDENT_TIER: &str = "com_dependent_tier";
/// `%def` definition dependent tier.
pub const DEF_DEPENDENT_TIER: &str = "def_dependent_tier";
/// Dependent tier line (generic).
pub const DEPENDENT_TIER: &str = "dependent_tier";
/// `%eng` English translation dependent tier.
pub const ENG_DEPENDENT_TIER: &str = "eng_dependent_tier";
/// `%err` error coding dependent tier.
pub const ERR_DEPENDENT_TIER: &str = "err_dependent_tier";
/// `%exp` explanation dependent tier.
pub const EXP_DEPENDENT_TIER: &str = "exp_dependent_tier";
/// `%fac` face dependent tier.
pub const FAC_DEPENDENT_TIER: &str = "fac_dependent_tier";
/// `%flo` flow dependent tier.
pub const FLO_DEPENDENT_TIER: &str = "flo_dependent_tier";
/// `%gls` gloss dependent tier.
pub const GLS_DEPENDENT_TIER: &str = "gls_dependent_tier";
/// `%gpx` gesture dependent tier.
pub const GPX_DEPENDENT_TIER: &str = "gpx_dependent_tier";
/// `%gra` grammatical relations dependent tier.
pub const GRA_DEPENDENT_TIER: &str = "gra_dependent_tier";
/// `%gra` tier prefix marker.
pub const GRA_TIER_PREFIX: &str = "gra_tier_prefix";
/// `%int` interpretation dependent tier.
pub const INT_DEPENDENT_TIER: &str = "int_dependent_tier";
/// `%mod` model dependent tier.
pub const MOD_DEPENDENT_TIER: &str = "mod_dependent_tier";
/// CST node type: `modsyl_dependent_tier`.
pub const MODSYL_DEPENDENT_TIER: &str = "modsyl_dependent_tier";
/// `%mor` morphology dependent tier.
pub const MOR_DEPENDENT_TIER: &str = "mor_dependent_tier";
/// `%mor` tier prefix marker.
pub const MOR_TIER_PREFIX: &str = "mor_tier_prefix";
/// `%ort` orthography dependent tier.
pub const ORT_DEPENDENT_TIER: &str = "ort_dependent_tier";
/// `%par` paralinguistic dependent tier.
pub const PAR_DEPENDENT_TIER: &str = "par_dependent_tier";
/// `%pho` phonology dependent tier.
pub const PHO_DEPENDENT_TIER: &str = "pho_dependent_tier";
/// `%pho` tier prefix marker.
pub const PHO_TIER_PREFIX: &str = "pho_tier_prefix";
/// CST node type: `phoaln_dependent_tier`.
pub const PHOALN_DEPENDENT_TIER: &str = "phoaln_dependent_tier";
/// CST node type: `phosyl_dependent_tier`.
pub const PHOSYL_DEPENDENT_TIER: &str = "phosyl_dependent_tier";
/// `%sin` dependent tier.
pub const SIN_DEPENDENT_TIER: &str = "sin_dependent_tier";
/// `%sin` tier prefix marker.
pub const SIN_TIER_PREFIX: &str = "sin_tier_prefix";
/// `%sit` situation dependent tier.
pub const SIT_DEPENDENT_TIER: &str = "sit_dependent_tier";
/// `%spa` speech act dependent tier.
pub const SPA_DEPENDENT_TIER: &str = "spa_dependent_tier";
/// `%tim` timing dependent tier.
pub const TIM_DEPENDENT_TIER: &str = "tim_dependent_tier";
/// Unrecognized dependent tier (parsed generically).
pub const UNSUPPORTED_DEPENDENT_TIER: &str = "unsupported_dependent_tier";
/// `%wor` original word dependent tier.
pub const WOR_DEPENDENT_TIER: &str = "wor_dependent_tier";
/// `%wor` tier prefix marker.
pub const WOR_TIER_PREFIX: &str = "wor_tier_prefix";
/// `%x` extension dependent tier.
pub const X_DEPENDENT_TIER: &str = "x_dependent_tier";

// === %mor Morphology Tier ===

/// Language code prefix in `%mor` word.
pub const LANGCODE: &str = "langcode";
/// Content of a single `%mor` word analysis.
pub const MOR_CONTENT: &str = "mor_content";
/// `%mor` tier contents: list of word analyses.
pub const MOR_CONTENTS: &str = "mor_contents";
/// Morphological feature on a `%mor` word.
pub const MOR_FEATURE: &str = "mor_feature";
/// Value of a morphological feature.
pub const MOR_FEATURE_VALUE: &str = "mor_feature_value";
/// Lemma (base form) in a `%mor` word analysis.
pub const MOR_LEMMA: &str = "mor_lemma";
/// Part-of-speech tag in a `%mor` word analysis.
pub const MOR_POS: &str = "mor_pos";
/// Post-clitic element in a `%mor` word analysis.
pub const MOR_POST_CLITIC: &str = "mor_post_clitic";
/// Single word analysis in `%mor` tier.
pub const MOR_WORD: &str = "mor_word";

// === %gra Grammatical Relations Tier ===

/// `%gra` tier contents: list of dependency relations.
pub const GRA_CONTENTS: &str = "gra_contents";
/// Head word index in a `%gra` dependency relation.
pub const GRA_HEAD: &str = "gra_head";
/// Word index in a `%gra` dependency relation.
pub const GRA_INDEX: &str = "gra_index";
/// Single dependency relation in `%gra` tier.
pub const GRA_RELATION: &str = "gra_relation";
/// Relation type name in a `%gra` dependency relation.
pub const GRA_RELATION_NAME: &str = "gra_relation_name";

// === %pho Phonology Tier ===

/// Opening marker for `%pho` alignment group.
pub const PHO_BEGIN_GROUP: &str = "pho_begin_group";
/// Closing marker for `%pho` alignment group.
pub const PHO_END_GROUP: &str = "pho_end_group";
/// Single alignment group in `%pho` tier.
pub const PHO_GROUP: &str = "pho_group";
/// Content inside a `%pho` alignment group.
pub const PHO_GROUPED_CONTENT: &str = "pho_grouped_content";
/// Container for `%pho` alignment groups.
pub const PHO_GROUPS: &str = "pho_groups";
/// Single word in `%pho` tier.
pub const PHO_WORD: &str = "pho_word";
/// Container for words in `%pho` tier.
pub const PHO_WORDS: &str = "pho_words";

// === %sin Tier ===

/// Opening marker for `%sin` alignment group.
pub const SIN_BEGIN_GROUP: &str = "sin_begin_group";
/// Closing marker for `%sin` alignment group.
pub const SIN_END_GROUP: &str = "sin_end_group";
/// Single alignment group in `%sin` tier.
pub const SIN_GROUP: &str = "sin_group";
/// Content inside a `%sin` alignment group.
pub const SIN_GROUPED_CONTENT: &str = "sin_grouped_content";
/// Container for `%sin` alignment groups.
pub const SIN_GROUPS: &str = "sin_groups";
/// Single word in `%sin` tier.
pub const SIN_WORD: &str = "sin_word";

// === %wor Original Word Tier ===

/// Body content of `%wor` tier.
pub const WOR_TIER_BODY: &str = "wor_tier_body";
/// Single word item in `%wor` tier.
pub const WOR_WORD_ITEM: &str = "wor_word_item";

// === Media and Timing ===

/// Timing bullet for media alignment (unified structured rule).
/// Used in utterance_end, base_content_item, text_with_bullets, wor_tier_body.
pub const BULLET: &str = "bullet";
/// Timestamp child inside a `bullet` node.
pub const BULLET_TIMESTAMP: &str = "bullet_timestamp";
/// Legacy alias (grammar renamed inline_bullet → bullet).
pub const INLINE_BULLET: &str = "inline_bullet";
/// Inline picture reference.
pub const INLINE_PIC: &str = "inline_pic";
/// Text content with timing bullets.
pub const TEXT_WITH_BULLETS: &str = "text_with_bullets";
/// Text content with timing bullets and pictures.
pub const TEXT_WITH_BULLETS_AND_PICS: &str = "text_with_bullets_and_pics";

// === Symbols and Punctuation ===

/// Ampersand symbol `&`.
pub const AMPERSAND: &str = "ampersand";
/// Break-for-coding marker `^`.
pub const BREAK_FOR_CODING: &str = "break_for_coding";
/// Colon symbol `:`.
pub const COLON: &str = "colon";
/// Comma symbol `,`.
pub const COMMA: &str = "comma";
/// Double quote character `"`.
pub const DOUBLE_QUOTE: &str = "double_quote";
/// Greater-than symbol `>`.
pub const GREATER_THAN: &str = "greater_than";
/// Hyphen symbol `-`.
pub const HYPHEN: &str = "hyphen";
/// Left square bracket `[`.
pub const LEFT_BRACKET: &str = "left_bracket";
/// Left double quotation mark.
pub const LEFT_DOUBLE_QUOTE: &str = "left_double_quote";
/// Less-than symbol `<`.
pub const LESS_THAN: &str = "less_than";
/// Non-colon separator in header content.
pub const NON_COLON_SEPARATOR: &str = "non_colon_separator";
/// Pipe symbol `|`.
pub const PIPE: &str = "pipe";
/// Plus symbol `+`.
pub const PLUS: &str = "plus";
/// Quoted new line within content.
pub const QUOTED_NEW_LINE: &str = "quoted_new_line";
/// Quoted period within content.
pub const QUOTED_PERIOD_SIMPLE: &str = "quoted_period_simple";
/// Right curly brace `}`.
pub const RIGHT_BRACE: &str = "right_brace";
/// Right square bracket `]`.
pub const RIGHT_BRACKET: &str = "right_bracket";
/// Right double quotation mark.
pub const RIGHT_DOUBLE_QUOTE: &str = "right_double_quote";
/// Semicolon symbol `;`.
pub const SEMICOLON: &str = "semicolon";
/// Generic separator element.
pub const SEPARATOR: &str = "separator";
/// Asterisk symbol `*`.
pub const STAR: &str = "star";
/// Tilde symbol `~`.
pub const TILDE: &str = "tilde";
/// Uptake symbol in utterance.
pub const UPTAKE_SYMBOL: &str = "uptake_symbol";
/// Zero morpheme marker `0`.
pub const ZERO: &str = "zero";

// === Whitespace ===

/// Newline character.
pub const NEWLINE: &str = "newline";
/// Space character.
pub const SPACE: &str = "space";
/// Tab character.
pub const TAB: &str = "tab";
/// Whitespace content (no semantic value).
pub const WHITESPACES: &str = "whitespaces";

// === Other ===

/// CST node type: `ethnicity_value`.
pub const ETHNICITY_VALUE: &str = "ethnicity_value";
/// CST node type: `form_marker`.
pub const FORM_MARKER: &str = "form_marker";
/// Free-text content for unstructured header values (e.g., @Location, @Situation).
pub const FREE_TEXT: &str = "free_text";
/// CST node type: `full_document`.
pub const FULL_DOCUMENT: &str = "full_document";
/// CST node type: `generic_date`.
pub const GENERIC_DATE: &str = "generic_date";
/// CST node type: `generic_id_ses`.
pub const GENERIC_ID_SES: &str = "generic_id_ses";
/// CST node type: `generic_id_sex`.
pub const GENERIC_ID_SEX: &str = "generic_id_sex";
/// CST node type: `generic_media_status`.
pub const GENERIC_MEDIA_STATUS: &str = "generic_media_status";
/// CST node type: `generic_media_type`.
pub const GENERIC_MEDIA_TYPE: &str = "generic_media_type";
/// CST node type: `generic_number`.
pub const GENERIC_NUMBER: &str = "generic_number";
/// CST node type: `generic_option_name`.
pub const GENERIC_OPTION_NAME: &str = "generic_option_name";
/// CST node type: `generic_recording_quality`.
pub const GENERIC_RECORDING_QUALITY: &str = "generic_recording_quality";
/// CST node type: `generic_time`.
pub const GENERIC_TIME: &str = "generic_time";
/// CST node type: `generic_transcription`.
pub const GENERIC_TRANSCRIPTION: &str = "generic_transcription";
/// CST node type: `lengthening`.
pub const LENGTHENING: &str = "lengthening";
/// Page number value.
pub const PAGE_NUMBER: &str = "page_number";
/// CST node type: `pos_tag`.
pub const POS_TAG: &str = "pos_tag";
/// CST node type: `ses_code_value`.
pub const SES_CODE_VALUE: &str = "ses_code_value";
/// CST node type: `ses_combined`.
pub const SES_COMBINED: &str = "ses_combined";
/// CST node type: `shortening`.
pub const SHORTENING: &str = "shortening";
/// CST node type: `source_file`.
pub const SOURCE_FILE: &str = "source_file";
/// CST node type: `stress_marker`.
pub const STRESS_MARKER: &str = "stress_marker";
/// CST node type: `strict_date`.
pub const STRICT_DATE: &str = "strict_date";
/// CST node type: `strict_time`.
pub const STRICT_TIME: &str = "strict_time";
/// Unrecognized line in document.
pub const UNSUPPORTED_LINE: &str = "unsupported_line";
/// CST node type: `word_body`.
pub const WORD_BODY: &str = "word_body";
/// CST node type: `word_lang_codes`.
pub const WORD_LANG_CODES: &str = "word_lang_codes";
/// CST node type: `word_lang_suffix`.
pub const WORD_LANG_SUFFIX: &str = "word_lang_suffix";
/// CST node type: `word_segment`.
pub const WORD_SEGMENT: &str = "word_segment";

// Total node types: 372
