//! REST API response structures — job info, results, health, listing.
//!
//! These are re-exported from [`super::api`] for backward compatibility.

use serde::{Deserialize, Serialize};

use crate::options::CommandOptions;
use crate::scheduling::{FailureCategory, LeaseRecord};

use super::domain::{
    ContentType, DisplayPath, DurationSeconds, HealthStatus, JobId, LanguageSpec, MemoryMb, NodeId,
    ReleasedCommand, UnixTimestamp,
};
use super::request::default_lang;
use super::status::{FileProgressStage, FileStatusKind, JobStatus};

// ---------------------------------------------------------------------------
// Response models
// ---------------------------------------------------------------------------

/// Result for a single processed file.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
pub struct FileResult {
    /// Display path for this file: a bare basename (`"sample.cha"`) or a
    /// relative forward-slash path (`"PWA/TYO_a1.cha"`) for directory input.
    /// Backslashes are normalized to forward slashes on construction.
    pub filename: DisplayPath,
    /// Processed file content (CHAT text or CSV).  Empty string when
    /// `error` is `Some`.
    #[serde(default)]
    pub content: String,
    /// MIME-like content discriminator: `"chat"` for CHAT files (default),
    /// `"csv"` for tabular output (e.g. opensmile features).
    #[serde(default)]
    pub content_type: ContentType,
    /// Human-readable error message if this file failed processing.
    /// `None` for successfully processed files.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Processing provenance extracted from the output CHAT file.
    /// Each entry records one batchalign3 command that was applied
    /// (command name, engine version, timestamp). Empty for non-CHAT
    /// output or files that failed processing.
    #[serde(default, skip_serializing_if = "Vec::is_empty")]
    pub provenance: Vec<crate::provenance::ProvenanceEntry>,
}

/// Per-file status within a job.
///
/// Tracks processing state, timing, progress, and error details for a
/// single file.  The server updates these entries as workers report
/// results, and they are included in `JobInfo.file_statuses`.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
pub struct FileStatusEntry {
    /// Display path for this file: a bare basename (`"sample.cha"`) or a
    /// relative forward-slash path (`"PWA/TYO_a1.cha"`) for directory input.
    /// Backslashes are normalized to forward slashes on construction.
    pub filename: DisplayPath,
    /// Current lifecycle state of this file.
    pub status: FileStatusKind,
    /// Human-readable error message.  Present only when `status` is `Error`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Broad classification of the failure. Helps the dashboard and retry
    /// logic group failures without parsing free-form messages.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_category: Option<FailureCategory>,
    /// CHAT validation error codes (e.g. `["E362", "E704"]`) when the failure
    /// was a validation rejection.  Empty or absent for non-validation errors.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_codes: Option<Vec<String>>,
    /// 1-based line number in the CHAT file where the first error was
    /// detected, if applicable.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error_line: Option<i64>,
    /// Opaque identifier linking to a persisted bug report (for post-mortem
    /// analysis).  Generated by the server when a file fails unexpectedly.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub bug_report_id: Option<String>,
    /// Unix timestamp (seconds since epoch) when the worker began processing
    /// this file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub started_at: Option<UnixTimestamp>,
    /// Unix timestamp (seconds since epoch) when processing finished
    /// (successfully or with error).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub finished_at: Option<UnixTimestamp>,
    /// When the file is deferred for a retry, the earliest unix timestamp at
    /// which another attempt should start. `None` when no retry is pending.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_eligible_at: Option<UnixTimestamp>,
    /// Number of sub-steps completed so far (e.g. utterances processed).
    /// Used with `progress_total` to drive progress bars.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress_current: Option<i64>,
    /// Total number of sub-steps expected for this file.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress_total: Option<i64>,
    /// Machine-readable code for the current in-flight processing stage.
    ///
    /// This is the stable field clients should use for branching or
    /// conditional UI. [`Self::progress_label`] is derived display text.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress_stage: Option<FileProgressStage>,
    /// Human-readable label for the current processing stage
    /// (e.g. "Morphosyntax", "Forced Alignment").
    ///
    /// This is derived from `progress_stage` by the server so operators can
    /// render friendly text without hard-coding label mappings in every UI.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub progress_label: Option<String>,
}

/// Control-plane backend that currently owns orchestration for a server job.
#[derive(Debug, Clone, Copy, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
#[serde(rename_all = "kebab-case")]
pub enum JobControlPlaneBackendKind {
    /// In-process local control plane.
    Local,
}

impl std::fmt::Display for JobControlPlaneBackendKind {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        match self {
            Self::Local => f.write_str("local"),
        }
    }
}

/// Backend-owned orchestration metadata for a job projection.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq, Eq)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
pub struct JobControlPlaneInfo {
    /// Control-plane backend that produced this projection.
    pub backend: JobControlPlaneBackendKind,
}

impl JobControlPlaneInfo {
    /// Local control-plane marker.
    pub fn local() -> Self {
        Self {
            backend: JobControlPlaneBackendKind::Local,
        }
    }
}

/// `GET /jobs/{id}` response — job progress.
///
/// Contains full detail about a single job, including per-file statuses.
/// Polled by the CLI to drive progress bars and by the dashboard for
/// live-updating tables.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
pub struct JobInfo {
    /// Server-assigned UUID (v4) for this job.
    pub job_id: JobId,
    /// Current lifecycle state of the job.
    pub status: JobStatus,
    /// Batchalign command that was submitted (e.g. "morphotag", "align").
    pub command: ReleasedCommand,
    /// Typed submitted command options captured at job creation time.
    ///
    /// The dashboard uses this to show the original argument/config payload for
    /// debugging and operator review without reconstructing a lossy CLI string.
    #[cfg_attr(feature = "server", schema(value_type = serde_json::Value))]
    pub options: CommandOptions,
    /// Language specification: a resolved ISO 639-3 code or `"auto"`.
    #[serde(default = "default_lang")]
    pub lang: LanguageSpec,
    /// Client's original input directory path, used for display in the
    /// dashboard and CLI output.  May be empty for content-mode submissions.
    #[serde(default)]
    pub source_dir: String,
    /// Total number of files in this job (immutable after submission).
    pub total_files: i64,
    /// Number of files that have finished processing (status `Done`).
    /// Invariant: `0 <= completed_files <= total_files`.
    pub completed_files: i64,
    /// Filename currently being processed.  `None` when the job is queued
    /// or has reached a terminal state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub current_file: Option<String>,
    /// Job-level error message (e.g. worker pool exhaustion, memory gate
    /// timeout).  Distinct from per-file errors in `file_statuses`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// Per-file processing status, one entry per submitted file.
    #[serde(default)]
    pub file_statuses: Vec<FileStatusEntry>,
    /// ISO 8601 timestamp of when the job was submitted (e.g.
    /// `"2026-01-15T10:00:00Z"`).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub submitted_at: Option<String>,
    /// IP address or Tailscale identifier of the submitting client.
    /// Used for conflict detection (same `submitted_by` + filename =
    /// duplicate).
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub submitted_by: Option<String>,
    /// Human-readable hostname of the submitting machine, resolved from
    /// Tailscale or reverse DNS.  For dashboard display only.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub submitted_by_name: Option<String>,
    /// ISO 8601 timestamp of when the job reached a terminal state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<String>,
    /// Wall-clock duration from first file dispatched to last file finished,
    /// in seconds.  `None` while the job is still active.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_s: Option<DurationSeconds>,
    /// When the job is deferred before execution, the earliest unix timestamp
    /// at which it should be retried. `None` when the job is immediately
    /// eligible to run.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_eligible_at: Option<UnixTimestamp>,
    /// Number of concurrent Python workers used for this job.  Determined
    /// by the pool at dispatch time.  `None` for queued jobs.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub num_workers: Option<i64>,
    /// Active lease information when this job is currently claimed by a node.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_lease: Option<LeaseRecord>,
    /// Per-language-group progress for batched text commands (morphotag,
    /// utseg, translate, coref).  Present only while a batch is in flight.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub batch_progress: Option<crate::runner::util::batch_progress::BatchInferProgress>,
    /// Server control-plane metadata for this job when returned by a server.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub control_plane: Option<JobControlPlaneInfo>,
    /// Execution plan describing where and how this job is processed.
    /// Present for staged-remote jobs; `None` for local execution.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub execution_plan: Option<crate::types::execution_plan::ExecutionPlan>,
    /// Wall-clock timestamp of the most recent cancel attempt against
    /// this job. `None` until at least one cancel arrives. Denormalized
    /// from the `cancellations` audit table for fast list-view rendering
    /// without a JOIN. See `CancellationRecord` for the full audit
    /// history via `GET /jobs/{id}/cancellations`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_cancelled_at: Option<UnixTimestamp>,
    /// Wire-format source string of the most recent cancel attempt
    /// (`tui`, `api`, `signal`, ...). See `CancelSource`.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_cancelled_source: Option<String>,
    /// Caller-reported host of the most recent cancel attempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_cancelled_host: Option<String>,
    /// Caller-reported reason of the most recent cancel attempt.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub last_cancelled_reason: Option<String>,
}

impl JobInfo {
    /// Attach server control-plane metadata to this job projection.
    pub fn with_control_plane(mut self, control_plane: JobControlPlaneInfo) -> Self {
        self.control_plane = Some(control_plane);
        self
    }
}

/// `GET /jobs/{id}/results` response — completed job results.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
pub struct JobResultResponse {
    /// Unique job identifier.
    pub job_id: JobId,
    /// Terminal status of the job.
    pub status: JobStatus,
    /// Per-file results (empty until the job completes).
    #[serde(default)]
    pub files: Vec<FileResult>,
}

/// Summary for job listing (`GET /jobs` response element).
///
/// A lighter-weight projection of [`JobInfo`] without per-file statuses,
/// suitable for listing many jobs at once.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
pub struct JobListItem {
    /// Server-assigned UUID (v4) for this job.
    pub job_id: JobId,
    /// Current lifecycle state of the job.
    pub status: JobStatus,
    /// Batchalign command (e.g. "morphotag", "align").
    pub command: ReleasedCommand,
    /// Language specification: a resolved ISO 639-3 code or `"auto"`.
    #[serde(default = "default_lang")]
    pub lang: LanguageSpec,
    /// Client's original input directory path, for display.
    #[serde(default)]
    pub source_dir: String,
    /// Total number of files in this job.
    pub total_files: i64,
    /// Number of files that finished successfully (`Done`).
    pub completed_files: i64,
    /// Number of files that ended in `Error` status.
    #[serde(default)]
    pub error_files: i64,
    /// Job-level error message when the job failed (the aggregated per-file
    /// failure reason). Surfaces the cause in the `/jobs` list and the live
    /// dashboard/TUI feed instead of a bare "failed". `None` for non-failed
    /// jobs. Distinct from per-file errors and from the `error_files` count.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub error: Option<String>,
    /// ISO 8601 timestamp of submission.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub submitted_at: Option<String>,
    /// IP address or Tailscale identifier of the submitting client.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub submitted_by: Option<String>,
    /// Human-readable hostname of the submitting machine.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub submitted_by_name: Option<String>,
    /// ISO 8601 timestamp of when the job reached a terminal state.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub completed_at: Option<String>,
    /// Wall-clock duration in seconds.  `None` while the job is active.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub duration_s: Option<DurationSeconds>,
    /// When the job is deferred before execution, the earliest unix timestamp
    /// at which it should be retried. `None` when immediately eligible.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub next_eligible_at: Option<UnixTimestamp>,
    /// Number of concurrent Python workers used for this job.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub num_workers: Option<i64>,
    /// Active lease information when this job is currently claimed by a node.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub active_lease: Option<LeaseRecord>,
    /// Server control-plane metadata for this job when returned by a server.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub control_plane: Option<JobControlPlaneInfo>,
}

impl JobListItem {
    /// Attach server control-plane metadata to this list projection.
    pub fn with_control_plane(mut self, control_plane: JobControlPlaneInfo) -> Self {
        self.control_plane = Some(control_plane);
        self
    }
}

/// `GET /health` response.
///
/// Provides a snapshot of server liveness, capacity, and operational
/// metrics. The CLI uses this for daemon version checks (`build_hash`) and
/// capability probing.
#[derive(Debug, Clone, Serialize, Deserialize, PartialEq)]
#[cfg_attr(feature = "server", derive(utoipa::ToSchema))]
pub struct HealthResponse {
    /// Server health status.  Always `Ok` in the current implementation
    /// (the endpoint itself being reachable implies health), but future
    /// versions may report degraded states.
    #[serde(default)]
    pub status: HealthStatus,
    /// Server software version (e.g. `"0.6.0"`).  Used by the CLI to
    /// detect stale daemons and auto-restart them.
    #[serde(default)]
    pub version: String,
    /// Identifier of the current server node.
    #[serde(default)]
    pub node_id: NodeId,
    /// Whether the Python workers are running on free-threaded Python
    /// (3.14t+).  Affects memory budgets and concurrency strategy.
    #[serde(default)]
    pub free_threaded: bool,
    /// Batchalign commands this server can process (e.g. `["morphotag",
    /// "align", "transcribe"]`).  Determined by probing worker capabilities
    /// at startup.
    #[serde(default)]
    pub capabilities: Vec<String>,
    /// Pipelines currently loaded in memory (warm workers).  A subset of
    /// `capabilities` — only commands whose workers have been spawned.
    #[serde(default)]
    pub loaded_pipelines: Vec<String>,
    /// Filesystem directories the server searches for media files (audio/video).
    /// Configured via `server.yaml` `media_roots`.
    #[serde(default)]
    pub media_roots: Vec<String>,
    /// Named keys from `server.yaml` `media_mappings`, each mapping a
    /// logical name (e.g. "childes-data") to a filesystem root.
    #[serde(default)]
    pub media_mapping_keys: Vec<String>,
    /// Backward-compat alias for `job_slots_available`.  Older clients read
    /// this field; newer clients prefer `job_slots_available`.
    #[serde(default)]
    pub workers_available: i64,
    /// Number of additional jobs the server can accept right now, based on
    /// memory and concurrency limits.
    #[serde(default)]
    pub job_slots_available: i64,
    /// Number of currently live Python worker processes.
    #[serde(default)]
    pub live_workers: i64,
    /// Active worker keys (`target:lang`) currently loaded in the pool.
    /// Infer-task workers use labels such as `infer:asr:eng`.
    #[serde(default)]
    pub live_worker_keys: Vec<String>,
    /// Number of jobs currently in `Queued` or `Running` state.
    #[serde(default)]
    pub active_jobs: i64,
    /// Utterance cache backend in use: `"sqlite"` (default).
    #[serde(default = "default_cache_backend")]
    pub cache_backend: String,
    /// Cumulative count of worker process crashes since server start.
    /// A high rate suggests resource exhaustion or buggy engine code.
    #[serde(default)]
    pub worker_crashes: i64,
    /// Cumulative count of work-unit attempts started since server start.
    #[serde(default)]
    pub attempts_started: i64,
    /// Cumulative count of attempts that were explicitly marked retryable.
    #[serde(default)]
    pub attempts_retried: i64,
    /// Cumulative count of work units that were deferred for later execution.
    #[serde(default)]
    pub deferred_work_units: i64,
    /// Cumulative count of files that were force-terminated (e.g. OOM-killed
    /// workers, stuck processes) since server start.
    #[serde(default)]
    pub forced_terminal_errors: i64,
    /// Backward-compat counter for job deferrals caused by host-memory
    /// admission pressure.
    #[serde(default)]
    pub memory_gate_aborts: i64,
    /// Build fingerprint — changes on every rebuild.  Used for stale-binary
    /// detection during development.  Empty string from older servers.
    #[serde(default)]
    pub build_hash: String,
    /// Background warmup lifecycle state: `"not_started"`, `"in_progress"`,
    /// or `"complete"`.  Clients can poll this to know when the server is
    /// fully ready for low-latency jobs.
    #[serde(default)]
    pub warmup_status: crate::worker::pool::WarmupStatus,

    // ── System memory snapshot ──────────────────────────────────────────
    /// Total physical memory in MB.
    #[serde(default)]
    pub system_memory_total_mb: MemoryMb,
    /// Available memory in MB (free + reclaimable).  On macOS this is
    /// `free + purgeable` which can undercount; see `sysinfo` docs.
    #[serde(default)]
    pub system_memory_available_mb: MemoryMb,
    /// Used memory in MB (`total - available`).
    #[serde(default)]
    pub system_memory_used_mb: MemoryMb,
    /// Host-memory reserve threshold in MB from server config.  0 means the
    /// coordinator will not keep explicit free-memory headroom.
    #[serde(default)]
    pub memory_gate_threshold_mb: MemoryMb,
    /// Host-memory pressure classification derived from current OS memory plus
    /// active cross-process reservations.
    #[serde(default)]
    pub host_memory_pressure: crate::host_memory::HostMemoryPressureLevel,
    /// Total memory currently reserved by the host-memory coordinator.
    #[serde(default)]
    pub host_memory_reserved_mb: MemoryMb,
    /// Number of active worker/model startup leases in the host coordinator.
    #[serde(default)]
    pub host_memory_startup_leases: i64,
    /// Number of active job-execution leases in the host coordinator.
    #[serde(default)]
    pub host_memory_job_leases: i64,
    /// Number of active machine-wide ML test locks in the host coordinator.
    #[serde(default)]
    pub host_memory_ml_test_locks: i64,
    /// Human-readable labels for active coordinator leases.
    #[serde(default)]
    pub host_memory_active_leases: Vec<String>,
    /// Snapshot error surfaced when the host-memory ledger cannot be read.
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub host_memory_error: Option<String>,
}

pub(crate) fn default_cache_backend() -> String {
    "sqlite".to_string()
}

#[cfg(test)]
mod tests {
    use super::*;

    /// Regression: the server returns relative paths like "PWA/TYO_a1.cha" as
    /// display names in file_statuses. These must deserialize successfully.
    /// Previously DisplayPath rejected path separators, causing "error decoding
    /// response body" on any job with files in subdirectories.
    #[test]
    fn job_info_deserializes_relative_path_filenames() {
        let json = r#"{
            "job_id": "abc-123",
            "status": "running",
            "command": "morphotag",
            "options": {"command": "morphotag", "retokenize": false, "skipmultilang": false, "merge_abbrev": false},
            "total_files": 2,
            "completed_files": 0,
            "file_statuses": [
                {"filename": "PWA/TYO_a1.cha", "status": "queued"},
                {"filename": "Control/TYO_n1.cha", "status": "queued"}
            ]
        }"#;
        let info: JobInfo = serde_json::from_str(json)
            .expect("JobInfo must deserialize file_statuses with relative-path display names");
        assert_eq!(info.file_statuses.len(), 2);
        assert_eq!(&*info.file_statuses[0].filename, "PWA/TYO_a1.cha");
    }
}
