//! Test module for generated in `talkbank-chat`.
//!
//! These tests document expected behavior and regressions.

// This file includes all auto-generated test modules from tests/generated/
// Tests in this directory are generated by:
// - bootstrap_spec_examples
// - bootstrap_reference_corpus

// Include all .rs files from the generated directory
mod generated {
    // Conditionally include generated test files
    // Each bootstrapper creates test files here
    include!("./generated/reference_corpus.rs");

    // Include spec test files dynamically by listing them
    // For now, we'll use reference_corpus as the main integration test
}
