//! Declarative subprocess coverage for command families and shared I/O modes.

mod cli_common;

use std::path::{Path, PathBuf};

use axum::{Json, Router, routing::get};
use cli_common::{CliHarness, MINIMAL_CHAT};

fn offline_harness() -> CliHarness {
    let harness = CliHarness::new();
    harness.disable_auto_daemon();
    harness
}

fn write_text(path: &Path, content: &str) {
    if let Some(parent) = path.parent() {
        std::fs::create_dir_all(parent).expect("mkdir parent");
    }
    std::fs::write(path, content).expect("write fixture");
}

fn write_chat(path: &Path) {
    write_text(path, MINIMAL_CHAT);
}

fn write_file_list(path: &Path, entries: &[&Path]) {
    let mut content = String::from("# generated by command_matrix.rs\n");
    for entry in entries {
        content.push_str(&entry.to_string_lossy());
        content.push('\n');
    }
    write_text(path, &content);
}

struct CommandExpectation {
    name: &'static str,
    args: Vec<String>,
    status: i32,
    stderr: &'static str,
    output_dir: Option<PathBuf>,
}

fn assert_command(harness: &CliHarness, case: &CommandExpectation) {
    let output = harness.cmd().args(&case.args).output().expect("run cli");
    let stdout = String::from_utf8_lossy(&output.stdout);
    let stderr = String::from_utf8_lossy(&output.stderr);

    assert_eq!(
        output.status.code(),
        Some(case.status),
        "{} returned unexpected exit code\nstdout:\n{}\nstderr:\n{}",
        case.name,
        stdout,
        stderr
    );
    assert!(
        stderr.contains(case.stderr),
        "{} stderr should contain {:?}\nstdout:\n{}\nstderr:\n{}",
        case.name,
        case.stderr,
        stdout,
        stderr
    );

    if let Some(out_dir) = &case.output_dir {
        assert!(
            out_dir.is_dir(),
            "{} should create output dir {}",
            case.name,
            out_dir.display()
        );
    }
}

async fn start_health_only_server(capabilities: &[&str]) -> String {
    let capabilities: Vec<String> = capabilities.iter().map(|cap| (*cap).to_string()).collect();
    let build_hash = batchalign::cli::build_hash().to_string();

    let router = Router::new().route(
        "/health",
        get(move || {
            let capabilities = capabilities.clone();
            let build_hash = build_hash.clone();
            async move {
                Json(serde_json::json!({
                    "status": "ok",
                    "version": "test-server",
                    "node_id": "test-node",
                    "capabilities": capabilities,
                    "workers_available": 1,
                    "job_slots_available": 1,
                    "build_hash": build_hash,
                }))
            }
        }),
    );

    let listener = tokio::net::TcpListener::bind("127.0.0.1:0")
        .await
        .expect("bind fake health server");
    let port = listener.local_addr().expect("local addr").port();

    tokio::spawn(async move {
        axum::serve(listener, router).await.ok();
    });

    format!("http://127.0.0.1:{port}")
}

#[test]
fn command_matrix_common_io_modes_reach_offline_dispatch() {
    let harness = offline_harness();
    let tmp = tempfile::TempDir::new().expect("tempdir");

    let corpus_file = tmp.path().join("corpus").join("sample.cha");
    write_chat(&corpus_file);

    let before_file = tmp.path().join("before").join("sample.cha");
    write_chat(&before_file);

    let file_list = tmp.path().join("inputs.txt");
    write_file_list(&file_list, &[&corpus_file]);

    let translate_out = tmp.path().join("translate-out");
    let compare_out = tmp.path().join("compare-out");
    let utseg_out = tmp.path().join("utseg-out");

    let cases = vec![
        CommandExpectation {
            name: "translate file-list output",
            args: vec![
                "translate".into(),
                "--file-list".into(),
                file_list.display().to_string(),
                "-o".into(),
                translate_out.display().to_string(),
            ],
            status: 0,
            stderr: "no server available",
            output_dir: Some(translate_out),
        },
        CommandExpectation {
            name: "coref in-place",
            args: vec![
                "coref".into(),
                "--in-place".into(),
                corpus_file.display().to_string(),
            ],
            status: 0,
            stderr: "no server available",
            output_dir: None,
        },
        CommandExpectation {
            name: "compare before output",
            args: vec![
                "compare".into(),
                corpus_file.display().to_string(),
                "-o".into(),
                compare_out.display().to_string(),
                "--before".into(),
                before_file.display().to_string(),
            ],
            status: 0,
            stderr: "no server available",
            output_dir: Some(compare_out),
        },
        CommandExpectation {
            name: "utseg file-list lang speakers",
            args: vec![
                "utseg".into(),
                "--lang".into(),
                "spa".into(),
                "-n".into(),
                "3".into(),
                "--file-list".into(),
                file_list.display().to_string(),
                "-o".into(),
                utseg_out.display().to_string(),
            ],
            status: 0,
            stderr: "no server available",
            output_dir: Some(utseg_out),
        },
    ];

    for case in &cases {
        assert_command(&harness, case);
    }
}

#[tokio::test(flavor = "multi_thread", worker_threads = 2)]
async fn command_matrix_explicit_server_rejects_unsupported_commands() {
    let harness = CliHarness::new();
    let tmp = tempfile::TempDir::new().expect("tempdir");
    let server_url = start_health_only_server(&["transcribe"]).await;

    let corpus_file = tmp.path().join("corpus").join("sample.cha");
    write_chat(&corpus_file);

    let opensmile_in = tmp.path().join("opensmile-in");
    std::fs::create_dir_all(&opensmile_in).expect("mkdir opensmile input");
    write_text(&opensmile_in.join("sample.wav"), "");

    let translate_out = tmp.path().join("translate-out");
    let coref_out = tmp.path().join("coref-out");
    let utseg_out = tmp.path().join("utseg-out");
    let compare_out = tmp.path().join("compare-out");
    let opensmile_out = tmp.path().join("opensmile-out");

    let cases = vec![
        CommandExpectation {
            name: "translate unsupported on explicit server",
            args: vec![
                "translate".into(),
                corpus_file.display().to_string(),
                "-o".into(),
                translate_out.display().to_string(),
                "--server".into(),
                server_url.clone(),
            ],
            status: 5,
            stderr: "does not support command 'translate'",
            output_dir: None,
        },
        CommandExpectation {
            name: "coref unsupported on explicit server",
            args: vec![
                "coref".into(),
                corpus_file.display().to_string(),
                "-o".into(),
                coref_out.display().to_string(),
                "--server".into(),
                server_url.clone(),
            ],
            status: 5,
            stderr: "does not support command 'coref'",
            output_dir: None,
        },
        CommandExpectation {
            name: "utseg unsupported on explicit server",
            args: vec![
                "utseg".into(),
                "--lang".into(),
                "spa".into(),
                corpus_file.display().to_string(),
                "-o".into(),
                utseg_out.display().to_string(),
                "--server".into(),
                server_url.clone(),
            ],
            status: 5,
            stderr: "does not support command 'utseg'",
            output_dir: None,
        },
        CommandExpectation {
            name: "compare unsupported on explicit server",
            args: vec![
                "compare".into(),
                corpus_file.display().to_string(),
                "-o".into(),
                compare_out.display().to_string(),
                "--server".into(),
                server_url.clone(),
            ],
            status: 5,
            stderr: "does not support command 'compare'",
            output_dir: None,
        },
        CommandExpectation {
            name: "opensmile unsupported on explicit server",
            args: vec![
                "opensmile".into(),
                opensmile_in.display().to_string(),
                opensmile_out.display().to_string(),
                "--server".into(),
                server_url,
            ],
            status: 5,
            stderr: "does not support command 'opensmile'",
            output_dir: None,
        },
    ];

    for case in &cases {
        assert_command(&harness, case);
    }
}

#[test]
fn command_matrix_invalid_paths_return_usage_errors() {
    let harness = offline_harness();
    let tmp = tempfile::TempDir::new().expect("tempdir");

    let empty_list = tmp.path().join("empty.txt");
    write_text(&empty_list, "# comments only\n\n");

    let missing_list = tmp.path().join("missing.txt");
    let missing_input = tmp.path().join("missing.cha");

    let cases = vec![
        CommandExpectation {
            name: "translate missing file list",
            args: vec![
                "translate".into(),
                "--file-list".into(),
                missing_list.display().to_string(),
            ],
            status: 2,
            stderr: "file list does not exist",
            output_dir: None,
        },
        CommandExpectation {
            name: "coref empty file list",
            args: vec![
                "coref".into(),
                "--file-list".into(),
                empty_list.display().to_string(),
            ],
            status: 2,
            stderr: "file list is empty",
            output_dir: None,
        },
        CommandExpectation {
            name: "compare missing input path",
            args: vec!["compare".into(), missing_input.display().to_string()],
            status: 2,
            stderr: "input path does not exist",
            output_dir: None,
        },
    ];

    for case in &cases {
        assert_command(&harness, case);
    }
}

#[test]
fn avqi_creates_output_dir_before_offline_dispatch() {
    let harness = offline_harness();
    let tmp = tempfile::TempDir::new().expect("tempdir");

    let input_dir = tmp.path().join("avqi-in");
    let output_dir = tmp.path().join("avqi-out");
    std::fs::create_dir_all(&input_dir).expect("mkdir avqi input");
    write_text(&input_dir.join("speaker.cs.wav"), "");
    write_text(&input_dir.join("speaker.sv.wav"), "");

    let case = CommandExpectation {
        name: "avqi offline output contract",
        args: vec![
            "avqi".into(),
            input_dir.display().to_string(),
            output_dir.display().to_string(),
            "--lang".into(),
            "eng".into(),
        ],
        status: 0,
        stderr: "no server available",
        output_dir: Some(output_dir),
    };

    assert_command(&harness, &case);
}

#[test]
fn opensmile_bank_requires_server() {
    let harness = offline_harness();
    let tmp = tempfile::TempDir::new().expect("tempdir");

    let input_dir = tmp.path().join("opensmile-in");
    let output_dir = tmp.path().join("opensmile-out");
    std::fs::create_dir_all(&input_dir).expect("mkdir opensmile input");
    write_text(&input_dir.join("sample.wav"), "");

    let case = CommandExpectation {
        name: "opensmile bank requires server",
        args: vec![
            "opensmile".into(),
            input_dir.display().to_string(),
            output_dir.display().to_string(),
            "--bank".into(),
            "childes-data".into(),
            "--subdir".into(),
            "Eng-NA".into(),
        ],
        status: 0,
        stderr: "--bank/--subdir remote media selection is no longer supported",
        output_dir: None,
    };

    assert_command(&harness, &case);
}
