use std::env;
use std::path::Path;

/// Vendored generated lexer (committed to repo, regenerated by re2rust on macOS).
const VENDORED_LEXER: &str = "src/generated/lexer.rs";

/// Generated Rust file name in OUT_DIR.
const LEXER_RUST_FILE: &str = "lexer.rs";

fn main() -> Result<(), Box<dyn std::error::Error>> {
    println!("cargo:rerun-if-changed={VENDORED_LEXER}");

    let out_dir = env::var("OUT_DIR").expect("OUT_DIR not set by Cargo");
    let out_path = Path::new(&out_dir).join(LEXER_RUST_FILE);

    // Copy the vendored (pre-generated) lexer to OUT_DIR.
    //
    // To regenerate (requires re2c 4.x — `brew install re2c` on macOS):
    //   re2rust -W -Wno-nondeterministic-tags --input-encoding utf8 --utf8 \
    //     --no-generation-date \
    //     --conditions -o src/generated/lexer.rs src/lexer.re
    //
    // `--no-generation-date` is REQUIRED: CI's "Verify vendored lexer is
    // up to date" job re-runs re2rust with the same flag and byte-diffs
    // the output against the committed file. Omitting it embeds a
    // timestamp header (`/* Generated by re2rust 4.5.1 on Wed … */`) that
    // never matches CI's timestamp-free output, and the job fails on
    // every push. See CLAUDE.md re2c-parser workflow.
    //
    // See lexer.re header comment for why -Wno-nondeterministic-tags is needed.
    std::fs::copy(VENDORED_LEXER, &out_path)?;

    Ok(())
}
