use chumsky::prelude::*;
use talkbank_model::model::Header;

use super::complex::{
    begin_gem_header_parser, birth_header_parser, birthplace_header_parser, date_header_parser,
    end_gem_header_parser, id_header_parser, l1_header_parser, languages_header_parser,
    lazy_gem_header_parser, media_header_parser, number_header_parser, options_header_parser,
    participants_header_parser, recording_quality_header_parser, time_duration_header_parser,
    time_start_header_parser, transcription_header_parser, types_header_parser,
};
use super::simple::{
    activities_header_parser, bck_header_parser, begin_header_parser, blank_header_parser,
    color_words_header_parser, comment_header_parser, end_header_parser, font_header_parser,
    location_header_parser, new_episode_header_parser, page_header_parser, pid_header_parser,
    room_layout_header_parser, situation_header_parser, tape_location_header_parser,
    thumbnail_header_parser, transcriber_header_parser, unknown_header_parser, utf8_header_parser,
    videos_header_parser, warning_header_parser, window_header_parser,
};

type HeaderParseResult<'a> = Result<Header, Vec<Rich<'a, char>>>;

fn parse_with<'a, P>(parser: P, input: &'a str) -> HeaderParseResult<'a>
where
    P: Parser<'a, &'a str, Header, extra::Err<Rich<'a, char>>>,
{
    parser.then_ignore(end()).parse(input).into_result()
}

pub(super) fn parse_known_header(input: &str) -> HeaderParseResult<'_> {
    match input.as_bytes() {
        [b'@', b'U', b'T', b'F', b'8', ..] => parse_with(utf8_header_parser(), input),
        [b'@', b'B', b'e', b'g', b'i', b'n', ..] => parse_with(begin_header_parser(), input),
        [b'@', b'E', b'n', b'd', ..] => parse_with(end_header_parser(), input),
        [
            b'@',
            b'N',
            b'e',
            b'w',
            b' ',
            b'E',
            b'p',
            b'i',
            b's',
            b'o',
            b'd',
            b'e',
            ..,
        ] => parse_with(new_episode_header_parser(), input),
        [
            b'@',
            b'L',
            b'a',
            b'n',
            b'g',
            b'u',
            b'a',
            b'g',
            b'e',
            b's',
            b':',
            ..,
        ] => parse_with(languages_header_parser(), input),
        [b'@', b'C', b'o', b'm', b'm', b'e', b'n', b't', b':', ..] => {
            parse_with(comment_header_parser(), input)
        }
        [
            b'@',
            b'P',
            b'a',
            b'r',
            b't',
            b'i',
            b'c',
            b'i',
            b'p',
            b'a',
            b'n',
            b't',
            b's',
            b':',
            ..,
        ] => parse_with(participants_header_parser(), input),
        [b'@', b'I', b'D', b':', ..] => parse_with(id_header_parser(), input),
        [b'@', b'P', b'I', b'D', b':', ..] => parse_with(pid_header_parser(), input),
        [b'@', b'D', b'a', b't', b'e', b':', ..] => parse_with(date_header_parser(), input),
        [b'@', b'M', b'e', b'd', b'i', b'a', b':', ..] => parse_with(media_header_parser(), input),
        [b'@', b'N', b'u', b'm', b'b', b'e', b'r', b':', ..] => {
            parse_with(number_header_parser(), input)
        }
        [
            b'@',
            b'R',
            b'e',
            b'c',
            b'o',
            b'r',
            b'd',
            b'i',
            b'n',
            b'g',
            b' ',
            b'Q',
            b'u',
            b'a',
            b'l',
            b'i',
            b't',
            b'y',
            b':',
            ..,
        ] => parse_with(recording_quality_header_parser(), input),
        [
            b'@',
            b'T',
            b'r',
            b'a',
            b'n',
            b's',
            b'c',
            b'r',
            b'i',
            b'p',
            b't',
            b'i',
            b'o',
            b'n',
            b':',
            ..,
        ] => parse_with(transcription_header_parser(), input),
        [
            b'@',
            b'S',
            b'i',
            b't',
            b'u',
            b'a',
            b't',
            b'i',
            b'o',
            b'n',
            b':',
            ..,
        ] => parse_with(situation_header_parser(), input),
        [b'@', b'T', b'y', b'p', b'e', b's', b':', ..] => parse_with(types_header_parser(), input),
        [
            b'@',
            b'T',
            b'a',
            b'p',
            b'e',
            b' ',
            b'L',
            b'o',
            b'c',
            b'a',
            b't',
            b'i',
            b'o',
            b'n',
            b':',
            ..,
        ] => parse_with(tape_location_header_parser(), input),
        [
            b'@',
            b'T',
            b'i',
            b'm',
            b'e',
            b' ',
            b'D',
            b'u',
            b'r',
            b'a',
            b't',
            b'i',
            b'o',
            b'n',
            b':',
            ..,
        ] => parse_with(time_duration_header_parser(), input),
        [
            b'@',
            b'T',
            b'i',
            b'm',
            b'e',
            b' ',
            b'S',
            b't',
            b'a',
            b'r',
            b't',
            b':',
            ..,
        ] => parse_with(time_start_header_parser(), input),
        [
            b'@',
            b'B',
            b'i',
            b'r',
            b't',
            b'h',
            b' ',
            b'o',
            b'f',
            b' ',
            ..,
        ] => parse_with(birth_header_parser(), input),
        [
            b'@',
            b'B',
            b'i',
            b'r',
            b't',
            b'h',
            b'p',
            b'l',
            b'a',
            b'c',
            b'e',
            b' ',
            b'o',
            b'f',
            b' ',
            ..,
        ] => parse_with(birthplace_header_parser(), input),
        [b'@', b'L', b'1', b' ', b'o', b'f', b' ', ..] => parse_with(l1_header_parser(), input),
        [b'@', b'F', b'o', b'n', b't', b':', ..] => parse_with(font_header_parser(), input),
        [b'@', b'W', b'i', b'n', b'd', b'o', b'w', b':', ..] => {
            parse_with(window_header_parser(), input)
        }
        [
            b'@',
            b'C',
            b'o',
            b'l',
            b'o',
            b'r',
            b' ',
            b'w',
            b'o',
            b'r',
            b'd',
            b's',
            b':',
            ..,
        ] => parse_with(color_words_header_parser(), input),
        [b'@', b'B', b'c', b'k', b':', ..] => parse_with(bck_header_parser(), input),
        [b'@', b'B', b'g', ..] => parse_with(begin_gem_header_parser(), input),
        [b'@', b'E', b'g', ..] => parse_with(end_gem_header_parser(), input),
        [b'@', b'G', b':', ..] => parse_with(lazy_gem_header_parser(), input),
        [b'@', b'T', b':', ..] => parse_with(thumbnail_header_parser(), input),
        [
            b'@',
            b'L',
            b'o',
            b'c',
            b'a',
            b't',
            b'i',
            b'o',
            b'n',
            b':',
            ..,
        ] => parse_with(location_header_parser(), input),
        [
            b'@',
            b'R',
            b'o',
            b'o',
            b'm',
            b' ',
            b'L',
            b'a',
            b'y',
            b'o',
            b'u',
            b't',
            b':',
            ..,
        ] => parse_with(room_layout_header_parser(), input),
        [
            b'@',
            b'T',
            b'r',
            b'a',
            b'n',
            b's',
            b'c',
            b'r',
            b'i',
            b'b',
            b'e',
            b'r',
            b':',
            ..,
        ] => parse_with(transcriber_header_parser(), input),
        [b'@', b'V', b'i', b'd', b'e', b'o', b's', b':', ..] => {
            parse_with(videos_header_parser(), input)
        }
        [b'@', b'O', b'p', b't', b'i', b'o', b'n', b's', b':', ..] => {
            parse_with(options_header_parser(), input)
        }
        [b'@', b'W', b'a', b'r', b'n', b'i', b'n', b'g', b':', ..] => {
            parse_with(warning_header_parser(), input)
        }
        [
            b'@',
            b'A',
            b'c',
            b't',
            b'i',
            b'v',
            b'i',
            b't',
            b'i',
            b'e',
            b's',
            b':',
            ..,
        ] => parse_with(activities_header_parser(), input),
        [b'@', b'B', b'l', b'a', b'n', b'k', ..] => parse_with(blank_header_parser(), input),
        [b'@', b'P', b'a', b'g', b'e', b':', ..] => parse_with(page_header_parser(), input),
        _ => parse_with(unknown_header_parser(), input),
    }
}
